version: "3.9"

services:
  db:
    image: postgres:15.6-alpine
    env_file: .env
    restart: unless-stopped
    command: >
      postgres
      -c shared_buffers=3GB
      -c work_mem=12MB
      -c maintenance_work_mem=1GB
      -c synchronous_commit=off
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - /tmp/gunicorn.sock:/tmp/gunicorn.sock
    restart: unless-stopped

  nginx:
    image: nginx:1.26-alpine
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/gunicorn.sock:/tmp/gunicorn.sock
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  pgdata:
